spring.application.name=SpringDemo
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# H2 Datasource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.security.user.password=demo@123
spring.security.user.name=admin
spring.app.jwtSecret=mySecretKey123912738askdjfjsadkjfdskfsadkfertyujsxcvbnrtyujikemdidk
spring.app.jwtExpirations_ms=3000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.bank.springdemo=DEBUG